### ISSUE TITLE
error at new storage account creation when cloning resource group in same subscription

### ISSUE THREAD

**Issue by MarvinWds** [JeffBow/AzurePowerShell#10]
Good morning,

We have been using the Clone-AzureRMresourceGroup.ps1 script to test the cloning of resource groups (production) to resource groups (accepting/testing).
The last test occured last summer. After that test run the original resource group was modified. The original resource group consisted of three vm's with a single disk and a fourth vm with an additional disk.
After modifications the resource group consisted of three vm's with a single disk and a fourth vm with three additional managed disks. After running the Clone-AzureRMresourceGroup.ps1 script on the modified resource group we ran into some issues regarding the cloning process.

The resource group is created but the storage account(s) are not. In order to troubleshoot the problem I created a simple testing resource in Azure (We use terraform the create resources in Azure).
I have listed what the powershell script does at first an also listed the error:

The following items will be copied:
Storage Accounts:
testing1201st1
Managed Disks:
Virtual Machines:
server1
server2
server3
server4
Operating system disks:
serverosdisk1
serverosdisk2
serverosdisk3
serverosdisk4
Data disks:
Current status of VMs:
server1 status is VM deallocated
server2 status is VM deallocated
server3 status is VM deallocated
server4 status is VM deallocated
Virtual networks:
cc-test
Network Security Groups:
nsg-test-server1
nsg-test-server2
nsg-test-server3
nsg-test-server4
Load Balancers:
Public IPs:
server1publicip
server1publicip
server1publicip
VERBOSE: Retrieving storage context for each source blob
Additional storage blobs:
VERBOSE: Creating new resource group clone_acceptatie in northeurope
The new resource group clone_acceptatie was created in subscription RelyTest01
VERBOSE: Creating storage account testing1201st1c1af887f in resource group clone_acceptatie at location northeurope
New-AzureRmStorageAccount : Cannot bind parameter 'EnableEncryptionService'. Cannot convert the "Microsoft.Azure.Manage
ment.Storage.Models.Encryption" value of type "Microsoft.Azure.Management.Storage.Models.Encryption" to type "System.Nullable`1[Microsoft.Azure.Commands.Management.Storage.StorageAccountBaseCmdlet+EncryptionSupportServiceEnum]".
At C:\Scripts\Clone-AzureRMresourceGroup.ps1:584 char:64
+ ... $newStorageAccount = New-AzureRmStorageAccount @storageParams -ea Sto ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmStorageAccount], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Management.Storage.NewAzureStora
   geAccountCommand

WARNING: Failed to create storage account. Storage account name testing1201st1c1af887f may already exists.
Enter a different Destination Storage Account Name: testing1201st2
VERBOSE: Creating storage account testing1201st2 in resource group clone_acceptatie at location northeurope
New-AzureRmStorageAccount : Cannot bind parameter 'EnableEncryptionService'. Cannot convert the "Microsoft.Azure.Manage
ment.Storage.Models.Encryption" value of type "Microsoft.Azure.Management.Storage.Models.Encryption" to type "System.Nullable`1[Microsoft.Azure.Commands.Management.Storage.StorageAccountBaseCmdlet+EncryptionSupportServiceEnum]".
At C:\Scripts\Clone-AzureRMresourceGroup.ps1:584 char:64
+ ... $newStorageAccount = New-AzureRmStorageAccount @storageParams -ea Sto ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmStorageAccount], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Management.Storage.NewAzureStora
   geAccountCommand

WARNING: Failed to create storage account. Storage account name testing1201st2 may already exists.
Enter a different Destination Storage Account Name:

It does not matter which storage account is entered, the same error keeps propping up. Is there something which has changed in Azure in the last six months regarding storage (and possibly storage encryption)?

Regards, Marvin Woods
Claranet Benelux, The Netherlands.

**Comment by JeffBow** [comment]
@MarvinWds   Thanks for the feedback.  I believe you're correct.   I only pass the required parameters of location, Name, ResourceGroupName and skuName.  Either the newer cmdlets require the EnableEncryptionService flag or it is picking it up from the source definition.  I'll investigate and try to get a fix posted soon.

**Comment by MarvinWds** [comment]
Hi Jeff,

Just this afternoon I was able to clone the resource group I created for
testing purposes. To achieve this I disabled the following lines:

# add CustomDomainName if present.
        #if($Encryption)
        #{
        #    $storageParams.Add("EnableEncryptionService", $Encryption)
        #}

This corresponds to your statement that the EnableEncryptionService needs
to be present, which was not the case in my environment.

What I will test for later if the clone script clones a server with a mix
of managed Premium_LRS and Standard_LRS disks. I will let you know how that
turns out.

Thanks for your e-mail and have a good weekend!

Regards, Marvin Woods

2018-01-19 23:10 GMT+01:00 Jeff Bowles <notifications@github.com>:

**Comment by JeffBow** [comment]
@MarvinWds   Good info. Thank you.   Actually that if() statement adds the -EnableEncryptionService flag if it is detected on the source account.  By disabling it, it allows it to be created but will not carry the encryption setting over from the source.   The value that I gather from the source to the new account must be the incorrect data type.  Thanks for narrowing it down.  It will make the fix much easier to complete.

**Comment by JeffBow** [comment]
@MarvinWds    Checked in a fix.  Let me know.  Thanks.

**Comment by MarvinWds** [comment]
Good afternoon Jeff,

Tried the new version, got the error below:

VERBOSE: Creating new resource group cc_clone in northeurope
The new resource group cc_clone was created in subscription RelyTest01
VERBOSE: Creating storage account clinidiag2058fxxxx in resource group cc_clone at location northe
urope
New-AzureRmStorageAccount : Cannot bind parameter 'EnableEncryptionService'. Cannot convert value
 "'Blob, File'" to type "Microsoft.Azure.Commands.Management.Storage.StorageAccountBaseCmdlet+Enc
ryptionSupportServiceEnum". Error: "Unable to match the identifier name 'Blob, File' to a valid e
numerator name. Specify one of the following enumerator names and try again:
None, Blob, File"
At C:\scripts\Clone-AzureRMresourceGroup_v2.ps1:590 char:64
+ ... $newStorageAccount = New-AzureRmStorageAccount @storageParams -ea Sto ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmStorageAccount], ParameterBinding 
   Exception
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Management 
   .Storage.NewAzureStorageAccountCommand
 
WARNING: Failed to create storage account. Storage account name clinidiag2058fxxxx may already exi
sts.
Enter a different Destination Storage Account Name: clinidiag3
VERBOSE: Creating storage account clinidiag3 in resource group cc_clone at location northeurope
New-AzureRmStorageAccount : Cannot bind parameter 'EnableEncryptionService'. Cannot convert value
 "'Blob, File'" to type "Microsoft.Azure.Commands.Management.Storage.StorageAccountBaseCmdlet+Enc
ryptionSupportServiceEnum". Error: "Unable to match the identifier name 'Blob, File' to a valid e
numerator name. Specify one of the following enumerator names and try again:
None, Blob, File"
At C:\scripts\Clone-AzureRMresourceGroup_v2.ps1:590 char:64
+ ... $newStorageAccount = New-AzureRmStorageAccount @storageParams -ea Sto ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmStorageAccount], ParameterBinding 
   Exception
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Management 
   .Storage.NewAzureStorageAccountCommand
 
WARNING: Failed to create storage account. Storage account name clinidiag3 may already exists.
Enter a different Destination Storage Account Name:

**Comment by jonsabbs** [comment]
I also got the same issue as described above and doing @MarvinWds encryption disablement allowed it to work again

**Comment by JeffBow** [comment]
@MarvinWds and @jonsabbs   Sorry for the delay.  Latest commit should fix it.

**Comment by fodip** [comment]
Hello,

After the encryption disablement I was able to continue with script, but at the moment to copy the VHD Blob it remain in "pending" status and never changes.


**VERBOSE: Checking VHD blob copy for container vhdblobs

Source      : https://blablabla.blob.core.windows.net/blablabla/blablabla-1
              %3D
Status      : Pending
BytesCopied : 662106112
TotalBytes  : 136367309312

Source      : https://blablabla.blob.core.windows.net/blablabla/blablabla-2
Status      : Pending
BytesCopied : 1306611712
TotalBytes  : 1098437886464

Source      : https://blablabla.blob.core.windows.net/blablabla/blablabla-3
Status      : Pending
BytesCopied : 674955264
TotalBytes  : 136367309312

Source      :https://blablabla.blob.core.windows.net/blablabla/blablabla-4
Status      : Pending
BytesCopied : 1359028224
TotalBytes  : 1098437886464

Source      : https://blablabla.blob.core.windows.net/blablabla/blablabla-5
Status      : Pending
BytesCopied : 1306599424
TotalBytes  : 1098437886464


WARNING: VHD blob copy is not complete
Press <Enter> to refresh or type EXIT and press <Enter> to quit copy status updates and resume later:** 


I changed the name of  source for security purpose just in case hehe. 

What can be done?  and when I used the -resume flag, only copy a couple of things from the RG source, leaving a lot of objects without copy to new RG.

Hope this can be fixed soon, thanks a lot for all your effort.

Regards

**Comment by JeffBow** [comment]
Thanks for the comments.  The status of PENDING on the blob copy is expected.  Are you not seeing progress when you refresh or return later using the -resume flag?  You should see the BytesCopied increase until it reaches the TotalBytes.  The return data you provided shows the copy process has started but has quite a bit left to complete.  I've seen it take upwards of 8 hours for larger resource groups and larger blob files when copying between different clouds and regions.  BTW. The encryption disablement should no longer be required.

**Comment by fodip** [comment]
Thanks for that clarification, to be honest didn't notice that detail. From portal was like blocked status. I continue worked migrating other components and when I checked again portal at next day everything was copied. Thanks for the quick response and support.

**Comment by hjoab** [comment]
I run this script but and error  
*************************************************************************************************************
PS C:\Users\ContainerAdministrator\CloudDrive> .\Clone-AzureRMresourceGroup.ps1

cmdlet Clone-AzureRMresourceGroup.ps1 at command pipeline position 1
Supply values for the following parameters:
ResourceGroupName: Testing
NewResourceGroupName: Test
Enter credentials for your Azure Subscription...
Login-AzureRmAccount : The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WindowsFormsWebAuthenticationDialogBase' threw an exception.:
Unable to load DLL 'IEFRAME.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
At C:\Users\ContainerAdministrator\CloudDrive\Clone-AzureRMresourceGroup.ps1:289 char:12
+    $login= Login-AzureRmAccount
+            ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

WARNING: Unable to acquire token for tenant '1aa3e053-81b6-4110-b562-1b9cf447a284'
Logged into Pay-As-You-Go with subscriptionID 61517ca3-91b1-4447-a74e-272163ed24fe as
WARNING: Get-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change release. The Name property for a Sku will return Standard_LRS and
 Premium_LRS
WARNING: Get-AzureRmVM: A property of the output of this cmdlet will change in an upcoming breaking change release. The StorageAccountType property for a DataDisk will return
 Standard_LRS and Premium_LRS
WARNING: No virtual machines found in resource group Testing

****************************************************************************************

In idea??
Thanks for any help

**Comment by hjoab** [comment]
After follow Marvin instructions to use ISE as admin I was able to run the script BUT.....
It found the VMs and said they were created but is not true and other stuff
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

PS C:\> \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1
cmdlet Clone-AzureRMresourceGroup.ps1 at command pipeline position 1
Supply values for the following parameters:
ResourceGroupName: cicd
NewResourceGroupName: test
Enter credentials for your Azure Subscription...
Logged into Pay-As-You-Go with subscriptionID 61517ca3-91b1-4447-a74e-272163ed24fe as holger@reemohealth.com
WARNING: Get-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change r
elease. The Name property for a Sku will return Standard_LRS and Premium_LRS
WARNING: Get-AzureRmVM: A property of the output of this cmdlet will change in an upcoming breaking change rel
ease. The StorageAccountType property for a DataDisk will return Standard_LRS and Premium_LRS
The following items will be copied:
Storage Accounts:
rhjenkinsagents
Managed Disks:
rhjenkins-disk0
rhjenkins-linux-slave-basicbaa040_OsDisk_1_02707b76b33b45d6b917b5740d9ce639
rhjenkins-linux-slave79e0d0_OsDisk_1_812cc4a775474d08be568b1f9ded75d8
Virtual Machines:
rhjenkins
rhjenkins-linux-slave-basicbaa040
rhjenkins-linux-slave79e0d0
Operating system disks:
rhjenkins-disk0
rhjenkins-linux-slave-basicbaa040_OsDisk_1_02707b76b33b45d6b917b5740d9ce639
rhjenkins-linux-slave79e0d0_OsDisk_1_812cc4a775474d08be568b1f9ded75d8
Data disks:
Current status of VMs:
WARNING: Get-AzureRmVM: A property of the output of this cmdlet will change in an upcoming breaking change rel
ease. The StorageAccountType property for a DataDisk will return Standard_LRS and Premium_LRS
rhjenkins status is VM deallocated
WARNING: Get-AzureRmVM: A property of the output of this cmdlet will change in an upcoming breaking change rel
ease. The StorageAccountType property for a DataDisk will return Standard_LRS and Premium_LRS
rhjenkins-linux-slave-basicbaa040 status is VM deallocated
WARNING: Get-AzureRmVM: A property of the output of this cmdlet will change in an upcoming breaking change rel
ease. The StorageAccountType property for a DataDisk will return Standard_LRS and Premium_LRS
rhjenkins-linux-slave79e0d0 status is VM deallocated
Virtual networks:
jenkinsarm-vnet
jenkinsvnet
Network Security Groups:
rhjenkins-nsg
Load Balancers:
Public IPs:
jenkinspip
rhjenkins-linux-slave-basicbaa040IPName
rhjenkins-linux-slave79e0d0IPName
VERBOSE: Retrieving storage context for each source blob
Additional storage blobs:
WARNING: test already exists.
Enter a different Resource Group Name: test2
VERBOSE: Creating new resource group test2 in eastus
The new resource group test2 was created in subscription Pay-As-You-Go
VERBOSE: Creating new managed disk rhjenkins-disk0 in eastus
WARNING: New-AzureRmDiskConfig: A property of the output of this cmdlet will change in an upcoming breaking ch
ange release. The Name property for a Sku will return Standard_LRS and Premium_LRS
WARNING: New-AzureRmDiskConfig: The accepted values for parameter SkuName will change in an upcoming breaking 
change release fromStandardLRS and PremiumLRS to Standard_LRS and Premium_LRS, respectively.
WARNING: New-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change r
elease. The Name property for a Sku will return Standard_LRS and Premium_LRS
New-AzureRmDisk : The request content was invalid and could not be deserialized: Required property 'name' 
not found in 'sku'.
ErrorCode: InvalidRequestContent
ErrorMessage: The request content was invalid and could not be deserialized: Required property 'name' not 
found in 'sku'.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : ee9a216a-715d-4a00-b733-e90e3fc84a20
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:758 char:27
+ ... newMDdisk = New-AzureRmDisk -ResourceGroupName $resourceGroupName -Di ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmDisk], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmDisk
 
The managed disk rhjenkins-disk0 was created.
VERBOSE: Creating new managed disk rhjenkins-linux-slave-basicbaa040_OsDisk_1_02707b76b33b45d6b917b5740d9ce639
 in eastus
WARNING: New-AzureRmDiskConfig: A property of the output of this cmdlet will change in an upcoming breaking ch
ange release. The Name property for a Sku will return Standard_LRS and Premium_LRS
WARNING: New-AzureRmDiskConfig: The accepted values for parameter SkuName will change in an upcoming breaking 
change release fromStandardLRS and PremiumLRS to Standard_LRS and Premium_LRS, respectively.
WARNING: New-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change r
elease. The Name property for a Sku will return Standard_LRS and Premium_LRS
New-AzureRmDisk : The request content was invalid and could not be deserialized: Required property 'name' 
not found in 'sku'.
ErrorCode: InvalidRequestContent
ErrorMessage: The request content was invalid and could not be deserialized: Required property 'name' not 
found in 'sku'.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 6820bffe-3eab-4747-8870-4a650477af99
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:758 char:27
+ ... newMDdisk = New-AzureRmDisk -ResourceGroupName $resourceGroupName -Di ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmDisk], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmDisk
 
The managed disk rhjenkins-linux-slave-basicbaa040_OsDisk_1_02707b76b33b45d6b917b5740d9ce639 was created.
VERBOSE: Creating new managed disk rhjenkins-linux-slave79e0d0_OsDisk_1_812cc4a775474d08be568b1f9ded75d8 in ea
stus
WARNING: New-AzureRmDiskConfig: A property of the output of this cmdlet will change in an upcoming breaking ch
ange release. The Name property for a Sku will return Standard_LRS and Premium_LRS
WARNING: New-AzureRmDiskConfig: The accepted values for parameter SkuName will change in an upcoming breaking 
change release fromStandardLRS and PremiumLRS to Standard_LRS and Premium_LRS, respectively.
WARNING: New-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change r
elease. The Name property for a Sku will return Standard_LRS and Premium_LRS
New-AzureRmDisk : The request content was invalid and could not be deserialized: Required property 'name' 
not found in 'sku'.
ErrorCode: InvalidRequestContent
ErrorMessage: The request content was invalid and could not be deserialized: Required property 'name' not 
found in 'sku'.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 59ceb936-f053-47cf-bcd6-b2b41b667a64
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:758 char:27
+ ... newMDdisk = New-AzureRmDisk -ResourceGroupName $resourceGroupName -Di ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmDisk], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmDisk
 
The managed disk rhjenkins-linux-slave79e0d0_OsDisk_1_812cc4a775474d08be568b1f9ded75d8 was created.
VERBOSE: Creating Network Security Group rhjenkins-nsg in resource group test2 at location eastus
Network Security Group rhjenkins-nsg was created
VERBOSE: Creating virtual network jenkinsarm-vnet in resource group test2 at location eastus
Virtual Network jenkinsarm-vnet was created
VERBOSE: Creating virtual network jenkinsvnet in resource group test2 at location eastus
Virtual Network jenkinsvnet was created
VERBOSE: Creating public IP jenkinspip in resource group test2 at location eastus
Public IP jenkinspip was created with DomainName Label cicdnew
VERBOSE: Creating public IP rhjenkins-linux-slave-basicbaa040IPName in resource group test2 at location eastus
Public IP rhjenkins-linux-slave-basicbaa040IPName was created with DomainName Label rhjenkins-linux-slave-basicbaa040new
VERBOSE: Creating public IP rhjenkins-linux-slave79e0d0IPName in resource group test2 at location eastus
Public IP rhjenkins-linux-slave79e0d0IPName was created with DomainName Label rhjenkins-linux-slave79e0d0new
VERBOSE: Adding IP config ipconfig1 to network interface rhjenkins-linux-slave-basicbaa040NIC
IP config ipconfig1 for rhjenkins-linux-slave-basicbaa040NIC was added
VERBOSE: Creating network interface rhjenkins-linux-slave-basicbaa040NIC in resource group test2 at location eastus
Network interface rhjenkins-linux-slave-basicbaa040NIC was created
VERBOSE: Adding IP config ipconfig1 to network interface rhjenkins-linux-slave79e0d0NIC
IP config ipconfig1 for rhjenkins-linux-slave79e0d0NIC was added
VERBOSE: Creating network interface rhjenkins-linux-slave79e0d0NIC in resource group test2 at location eastus
Network interface rhjenkins-linux-slave79e0d0NIC was created
VERBOSE: Adding IP config ipconfig1 to network interface rhjenkins-nic
IP config ipconfig1 for rhjenkins-nic was added
VERBOSE: Creating network interface rhjenkins-nic in resource group test2 at location eastus
Network interface rhjenkins-nic was created
WARNING: Get-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change release. The Name propert
y for a Sku will return Standard_LRS and Premium_LRS
Get-AzureRmDisk : The Resource 'Microsoft.Compute/disks/rhjenkins-disk0' under resource group 'test2' was not found.
ErrorCode: ResourceNotFound
ErrorMessage: The Resource 'Microsoft.Compute/disks/rhjenkins-disk0' under resource group 'test2' was not found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 4d9ef225-f918-499a-adef-c53a32cb31f2
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1490 char:22
+ ... osDiskId = (Get-AzureRmDisk -DiskName $OSDiskName -ResourceGroupName  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDisk], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureRmDisk
 
Set-AzureRmVMOSDisk : Cannot validate argument on parameter 'ManagedDiskId'. The argument is null or empty. Provide an argument that 
is not null or empty, and then try the command again.
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1498 char:104
+ ... VM $VirtualMachine -Name $OSDiskName -ManagedDiskId $osDiskId -Cachin ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmVMOSDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Compute.SetAzureVMOSDiskCommand
 
WARNING: Add-AzureRmVMNetworkInterface: A property of the output of this cmdlet will change in an upcoming breaking change release. Th
e StorageAccountType property for a DataDisk will return Standard_LRS and Premium_LRS
VERBOSE: Creating Virtual Machine rhjenkins in resource group test2 at location eastus
New-AzureRmVM : Required parameter 'storageProfile' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'storageProfile' is missing (null).
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : c50867e0-8790-4c89-a879-fa8a70179b9e
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1566 char:9
+         New-AzureRmVM -ResourceGroupName $ResourceGroupName -Location ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand
 
WARNING: Failed to create Virtual Machine rhjenkins
WARNING: Get-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change release. The Name propert
y for a Sku will return Standard_LRS and Premium_LRS
Get-AzureRmDisk : The Resource 'Microsoft.Compute/disks/rhjenkins-linux-slave-basicbaa040_OsDisk_1_02707b76b33b45d6b917b5740d9ce639' 
under resource group 'test2' was not found.
ErrorCode: ResourceNotFound
ErrorMessage: The Resource 'Microsoft.Compute/disks/rhjenkins-linux-slave-basicbaa040_OsDisk_1_02707b76b33b45d6b917b5740d9ce639' 
under resource group 'test2' was not found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 7bbceaab-55d7-4d56-b5e6-1672a6e164af
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1490 char:22
+ ... osDiskId = (Get-AzureRmDisk -DiskName $OSDiskName -ResourceGroupName  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDisk], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureRmDisk
 
Set-AzureRmVMOSDisk : Cannot validate argument on parameter 'ManagedDiskId'. The argument is null or empty. Provide an argument that 
is not null or empty, and then try the command again.
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1498 char:104
+ ... VM $VirtualMachine -Name $OSDiskName -ManagedDiskId $osDiskId -Cachin ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmVMOSDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Compute.SetAzureVMOSDiskCommand
 
WARNING: Add-AzureRmVMNetworkInterface: A property of the output of this cmdlet will change in an upcoming breaking change release. Th
e StorageAccountType property for a DataDisk will return Standard_LRS and Premium_LRS
VERBOSE: Creating Virtual Machine rhjenkins-linux-slave-basicbaa040 in resource group test2 at location eastus
New-AzureRmVM : Required parameter 'storageProfile' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'storageProfile' is missing (null).
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 3b4aabdf-2e8c-42ec-8eac-af7bbe94c29c
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1566 char:9
+         New-AzureRmVM -ResourceGroupName $ResourceGroupName -Location ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand
 
WARNING: Failed to create Virtual Machine rhjenkins-linux-slave-basicbaa040
WARNING: Get-AzureRmDisk: A property of the output of this cmdlet will change in an upcoming breaking change release. The Name propert
y for a Sku will return Standard_LRS and Premium_LRS
Get-AzureRmDisk : The Resource 'Microsoft.Compute/disks/rhjenkins-linux-slave79e0d0_OsDisk_1_812cc4a775474d08be568b1f9ded75d8' under 
resource group 'test2' was not found.
ErrorCode: ResourceNotFound
ErrorMessage: The Resource 'Microsoft.Compute/disks/rhjenkins-linux-slave79e0d0_OsDisk_1_812cc4a775474d08be568b1f9ded75d8' under 
resource group 'test2' was not found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 67fa878b-a1c5-4f66-9d8f-b88d3fab2a9e
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1490 char:22
+ ... osDiskId = (Get-AzureRmDisk -DiskName $OSDiskName -ResourceGroupName  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDisk], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureRmDisk
 
Set-AzureRmVMOSDisk : Cannot validate argument on parameter 'ManagedDiskId'. The argument is null or empty. Provide an argument that 
is not null or empty, and then try the command again.
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1498 char:104
+ ... VM $VirtualMachine -Name $OSDiskName -ManagedDiskId $osDiskId -Cachin ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmVMOSDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Compute.SetAzureVMOSDiskCommand
 
WARNING: Add-AzureRmVMNetworkInterface: A property of the output of this cmdlet will change in an upcoming breaking change release. Th
e StorageAccountType property for a DataDisk will return Standard_LRS and Premium_LRS
VERBOSE: Creating Virtual Machine rhjenkins-linux-slave79e0d0 in resource group test2 at location eastus
New-AzureRmVM : Required parameter 'storageProfile' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'storageProfile' is missing (null).
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 150584c0-935a-404a-ae82-6c5a9483dca9
At \\T430\d\GitHub\Reemo\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:1566 char:9
+         New-AzureRmVM -ResourceGroupName $ResourceGroupName -Location ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand
 
WARNING: Failed to create Virtual Machine rhjenkins-linux-slave79e0d0

PS C:\>
