### ISSUE TITLE
Storage Account Encryption Error in Copy-AzureRMresourceGroup

### ISSUE THREAD

**Issue by wthenrichs** [JeffBow/AzurePowerShell#12]
The Copy-AzureRMresourceGroup.ps1 script gave me an error when attempting to create the storage account in the new resource group.

Looking at the source, I saw that the $EncryptionType variable wasn't used in the storage params. After updating the script to use this value the cmdlet ran without issue.

**Comment by JeffBow** [comment]
Thank you @wthenrichs We recently changed this section based on an issue with the Clone version of this script, but I erroneously forgot to change the variable name to $EncryptionType :-(
