### ISSUE TITLE
Issues with New-AzureRmDisk  when cloning with Module AzureRM 6.1.1

### ISSUE THREAD

**Issue by HenryT88** [JeffBow/AzurePowerShell#14]
Hello @JeffBow 
I have been using the Clone-AzureRMresourceGroup.ps1 script to successfully clone Resource Groups for over 6 months now.
Yesterday I updated Powershell Module AzureRM to version 6.1.1

Clone-AzureRMresourceGroup.ps1 has started failing when attempting to create a new managed Disk on the new resource group.  This occurs for any attempt made.

```
New-AzureRmDisk : The request content was invalid and could not be
deserialized: Required property 'name' not found in 'sku'.
ErrorCode: InvalidRequestContent
ErrorMessage: The request content was invalid and could not be
deserialized: Required property 'name' not found in 'sku'.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : de9b7234-7a5f-4153-83bc-67c82374cd88
At C:\W_DRIVE\Azure Demo
Management\AzurePowerShell\Clone-AzureRMresourceGroup.ps1:760 char:27
+ ... newMDdisk = New-AzureRmDisk -ResourceGroupName $resourceGroupName
-Di ...
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmDisk], Compute
   CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automatio
   n.NewAzureRmDisk
```

I was able to reinstall module AzureRM 4.4.1 and is working with no issues.

I am not sure how to diagnose further?  
Hoping can help - as I would like to use the latest version of AzureRM if possible.

**Comment by JeffBow** [comment]
@HenryT88   Looks like the 6.0.1 version of  New-AzureRmVmDiskConfig replaced the -AccountType flag with -SkuName.  Should be an easy fix.

**Comment by HenryT88** [comment]
Thanks @JeffBow, 
That update has resolved the issue.
