### ISSUE TITLE
Copy-AzureRMresourceGroup does not work because Grant-AzureRmDiskAccess AccessSAS returns null

### ISSUE THREAD

**Issue by JeffBow** [JeffBow/AzurePowerShell#15]
Reference https://github.com/Azure/azure-powershell/issues/5956  

This will only effect managed disks.

**Comment by pafnow** [comment]
Same issue here

**Comment by HenryT88** [comment]
This also affects Clone-AzureRMresourceGroup.ps1 when using the -newLocation  parameter.

**Comment by JeffBow** [comment]
The issue with Grant-AzureRmDiskAccess appears to be resolved in AzureRM.Compute version 5.2.0  (i.e. run **Update-Module AzureRM** to get to AzureRM 6.4.0)
