### ISSUE TITLE
Multiple Script Errors when copying from a storage account

### ISSUE THREAD

**Issue by atindula** [JeffBow/AzurePowerShell#16]
1. Missing closing } starting at line 559
2. Encryption piece errors out on parameters.  It appears the latest version of New-AzureRMStorageAccount doesn't even take an encryption parameter.  Commenting out this section has the script function until it gets to the final VM creation.
3. New-AzureRmVM : Required parameter 'networkProfile' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'networkProfile' is missing (null).
StatusCode: 400
4. Add-AzureRmVMDataDisk : Cannot validate argument on parameter 'VhdUri'. The argument is null or empty. Provide an argument that is 
not null or empty, and then try the command again.
5. Copy-AzureRMresourceGroupv2.ps1:1581 char:21
+ ... $newNICs += Get-AzureRmNetworkInterface -Name $NICName -ResourceGroup ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmNetworkInterface], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureNetworkInterfaceCommand

For reference I am copying a vm attached to a storage account between subscriptions.  It is a single linux vm with 1 extra data disk.  I have run the Update-Module AzureRM command and am using the  latest version of PowerShell.  Any help would be appreciated.

**Comment by soyanede** [comment]
Hello,
With respect to point 1, I believe that the corresponding missing closing key } must go on line 1017.
Regarding the other points, I can not give much help.
I attach a file with that small correction.
Regards.
[Copy-AzureRMresourceGroup.zip](https://github.com/JeffBow/AzurePowerShell/files/2303759/Copy-AzureRMresourceGroup.zip)

**Comment by JeffBow** [comment]
@atindula  Thank for finding this.   @soyanede  You are correct and that fix will be added to the others.   Seems we have problems with the newer modules as it pertains to managed disks.  It appears the VHD property is no longer returned, and I was using that. Fixes are in the works.

**Comment by JeffBow** [comment]
@atindula.  The latest check in should fix the reported issues.  It wasn't the vhd property after all. I had handled that properly in past updates, but rather **Set-AzureRmVMOSDisk** now requires -StorageAccountType when using managed disk

**Comment by JeffBow** [comment]
Successfully tested the Copy and Clone scripts using AzureRM 6.7

**Comment by atindula** [comment]
@JeffBow Thank you for your work on the script.  I will be testing this soon.  For some reason the issue updates got trapped in spam.
