### ISSUE TITLE
Source Account Creds with access to multiple Tenants Breaks

### ISSUE THREAD

**Issue by hgoodrow** [JeffBow/AzurePowerShell#3]
I have an account which has access to 5 different Subscriptions across two AAD tenants.  Line 286 is #$sub = Get-AzureRmSubscription -TenantID $login.context.Subscription.TenantID which passes a given Tenant ID for the source account.  In my case, since I only had 1 Subscription in the AAD Tenant, I was never prompted for the Select-AzureRmSubscription dialogue.  I removed the -TenantID flag which looks like this now: $sub = Get-AzureRmSubscription  and it works fine.

**Comment by JeffBow** [comment]
By design it will not prompt you to choose the subscription if you only have one subscription for a tenant, but the -TenantID flag was not doing what I wanted (preventing carry-over) from previous $login so I removed it per the recommendation of @hgoodrow   Thank you.
