### ISSUE TITLE
Do you have any of the same scripting for PAAS resources?

### ISSUE THREAD

**Issue by crshnbrn66** [JeffBow/AzurePowerShell#4]
Wondered if you had done any app service cloning or Application Insights cloning?

**Comment by JeffBow** [comment]
@crshnbrn66  Not yet.  I'm currently working on Azure Automation components but eventually want to add PAAS pieces.   Looking for assistance if anyone is willing to help

**Comment by crshnbrn66** [comment]
Ok I'll help where and when I can.
