### ISSUE TITLE
Migrating credentials failure

### ISSUE THREAD

**Issue by KobusOlie4** [JeffBow/AzurePowerShell#7]
Hi, I am testing this script for an upcoming migration and get the error: 
Enter credentials for the 'source' Azure Subscription...
WARNING: The provided credentials failed to authenticate or are not associcated to a valid subscription. Exiting the script 
I have ensured that I have the correct credentials but to no avail - any assistance will be appreciated. Thank you.

**Comment by JeffBow** [comment]
@KobusOlie4   Which version of AzureRM.Profile are you using?  Use Get-Command Login-AzureRmAccount to find out.  Also, is there a SubscriptionID when you use Get-AzureRMSubscription after logging in with the same credentials you use to execute the script?

**Comment by JeffBow** [comment]
@KobusOlie4  I confirmed it is the newer modules causing your problem.  AzureRM version 3.2 used SubscriptionID, but now that property is just ID in 4.2.1.  I'll check that fix in when I add the Managed Disk support, but for now you can import-module AzureRM -Requiredversion 3.2.0 as workaround.

**Comment by JeffBow** [comment]
Resolved in the latest release.
