### ISSUE TITLE
Clone-AzureRMresourceGroup.ps1 fails at Set-AzureRmVMOSDisk if Linux VM

### ISSUE THREAD

**Issue by hounster** [JeffBow/AzurePowerShell#9]
See Error:

Set-AzureRmVMOSDisk : Cannot validate argument on parameter 'ManagedDiskId'. The argument is null or empty. Provide an argument that is not null
or empty, and then try the command again.
At C:\Users\Calhoun.Clark\Documents\WindowsPowershell\scripts\AzurePowershell\Clone-AzureRMresourceGroup.ps1:1492 char:104
+ ... M $VirtualMachine -Name $OSDiskName -ManagedDiskId $osDisk.Id -Cachin ...
+                                                        ~~~~~~~~~~

"$osDisk.Id" in above code line should be "$osDiskId"

**Comment by JeffBow** [comment]
@hounster Thank you!  Fix has been checked in for this file and the copy-azureRmResourceGroup.ps1
